from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Iterable, Optional

import pandas as pd

from app.analysis.models import (
    Direction,
    EventType,
    MarketEvent,
)


@dataclass
class EventRegistry:
    """
    Stores and manages all market events generated by the analysis engine.

    Examples:
        BOS
        MSS
        CHoCH
        Liquidity created
        Liquidity swept
        Liquidity broken
        Order block created
        FVG created
    """

    events: list[MarketEvent] = field(default_factory=list)

    def add(self, event: MarketEvent) -> None:
        """
        Add one event to the registry.

        Event IDs must be unique.
        """

        if self.get_by_id(event.event_id) is not None:
            raise ValueError(
                f"Market event already exists: {event.event_id}"
            )

        self.events.append(event)

    def extend(
        self,
        events: Iterable[MarketEvent],
    ) -> None:
        """
        Add multiple events to the registry.
        """

        for event in events:
            self.add(event)

    def get_by_id(
        self,
        event_id: str,
    ) -> Optional[MarketEvent]:
        """
        Return one event by its unique ID.
        """

        for event in self.events:
            if event.event_id == event_id:
                return event

        return None

    def all(
        self,
        *,
        sorted_by_time: bool = False,
    ) -> list[MarketEvent]:
        """
        Return all registered events.

        Set sorted_by_time=True to return events in chronological order.
        """

        events = list(self.events)

        if sorted_by_time:
            events.sort(
                key=lambda event: (
                    event.time,
                    event.index,
                    event.event_id,
                )
            )

        return events

    def by_type(
        self,
        event_type: EventType,
    ) -> list[MarketEvent]:
        """
        Return events matching one event type.
        """

        return [
            event
            for event in self.events
            if event.event_type == event_type
        ]

    def by_direction(
        self,
        direction: Direction,
    ) -> list[MarketEvent]:
        """
        Return events matching one direction.
        """

        return [
            event
            for event in self.events
            if event.direction == direction
        ]

    def by_source_id(
        self,
        source_id: str,
    ) -> list[MarketEvent]:
        """
        Return all events associated with a source object.

        Example:
            EQH_2
            EQL_1
            OB_4
            FVG_7
        """

        return [
            event
            for event in self.events
            if event.source_id == source_id
        ]

    def by_source_type(
        self,
        source_type: str,
    ) -> list[MarketEvent]:
        """
        Return all events matching a source type.

        Example:
            BSL
            SSL
            MARKET_STRUCTURE
            ORDER_BLOCK
            FVG
        """

        return [
            event
            for event in self.events
            if event.source_type == source_type
        ]

    def between(
        self,
        start_time: datetime,
        end_time: datetime,
    ) -> list[MarketEvent]:
        """
        Return events between two datetimes, inclusive.
        """

        if end_time < start_time:
            raise ValueError(
                "end_time cannot be earlier than start_time."
            )

        return [
            event
            for event in self.events
            if start_time <= event.time <= end_time
        ]

    def latest(
        self,
        event_type: EventType | None = None,
        direction: Direction | None = None,
    ) -> Optional[MarketEvent]:
        """
        Return the latest matching event.

        Optional filters:
            event_type
            direction
        """

        candidates = self.events

        if event_type is not None:
            candidates = [
                event
                for event in candidates
                if event.event_type == event_type
            ]

        if direction is not None:
            candidates = [
                event
                for event in candidates
                if event.direction == direction
            ]

        if not candidates:
            return None

        return max(
            candidates,
            key=lambda event: (
                event.time,
                event.index,
                event.event_id,
            ),
        )

    def count(
        self,
        event_type: EventType | None = None,
        direction: Direction | None = None,
    ) -> int:
        """
        Count events using optional filters.
        """

        candidates = self.events

        if event_type is not None:
            candidates = [
                event
                for event in candidates
                if event.event_type == event_type
            ]

        if direction is not None:
            candidates = [
                event
                for event in candidates
                if event.direction == direction
            ]

        return len(candidates)

    def to_list(
        self,
        *,
        sorted_by_time: bool = True,
    ) -> list[dict]:
        """
        Convert all events to serialisable dictionaries.
        """

        return [
            event.to_dict()
            for event in self.all(
                sorted_by_time=sorted_by_time
            )
        ]

    def to_dataframe(
        self,
        *,
        sorted_by_time: bool = True,
    ) -> pd.DataFrame:
        """
        Convert all registered events into a DataFrame.
        """

        data = self.to_list(
            sorted_by_time=sorted_by_time
        )

        if not data:
            return pd.DataFrame()

        return pd.DataFrame(data)

    def __len__(self) -> int:
        return len(self.events)

    def __iter__(self):
        return iter(self.events)